### ISSUE TITLE
NoClassDefFoundError: HiltViewModelFactory after updating to Hilt 2.57.1

### ISSUE THREAD

**Issue by KhunHtetzNaing** [sebaslogen/resaca#226]
After upgrading to Hilt `2.57.1`, the app crashes at runtime with:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/hilt/navigation/HiltViewModelFactory;
```

It works fine on `2.57`.

**Environment:**

* Hilt: `2.57.1`
* Resaca: `4.5.0`
* AGP: `8.13.0`

**Comment by sebaslogen** [comment]
@KhunHtetzNaing the PR build fails because the updated import is not part of Hilt 2.57.1:

>  e: file:///home/runner/work/resaca/resaca/resacahilt/src/main/java/com/sebaslogen/resaca/hilt/ScopedMemoizers.kt:10:22 Unresolved reference 'lifecycle'.
e: file:///home/runner/work/resaca/resaca/resacahilt/src/main/java/com/sebaslogen/resaca/hilt/ScopedMemoizers.kt:294:9 Unresolved reference 'HiltViewModelFactory'.

Apparently, the import updated lib in your PR is available in hilt-navigation-compose 1.3.0, can you please check if that is also the library version you were using in your project when you encountered the NoClassDefFoundError?

**Comment by sebaslogen** [comment]
Problem introduced with breaking change on hilt-navigation-compose 1.3.0 has been fixed on https://github.com/sebaslogen/resaca/commit/5f0b26778c601866e1475e9a75272f5e15b7190e

A new version of Resaca with this fix and other dependencies updates would be released soon.

**Comment by KhunHtetzNaing** [comment]
Thanks 🙏

**Comment by sebaslogen** [comment]
Release 4.6.0 with fix is available https://github.com/sebaslogen/resaca/releases/tag/4.6.0
